### PR TITLE
Add script to generate quick links table

### PR DESCRIPTION
**Pull request by weshaggard**
Add a script that will generate the quick links table as well
as verify that all the links work correctly.

@kaerm @adrianhall Can you guys please take a look. Right now this is only for .NET but I'm actively planning to update this PR with the other languages as well. I just wanted to get something out for review. 

@AlexGhiondea @chidozieononiwu could you guys have a look over the link format for .NET?

### CODE REVIEW

**Comment by pakrym** [comment]
Can we add this to the `CodeChecks.ps1` so it's verified during the CI runs?

**Comment by weshaggard** [comment]
What `CodeChecks.ps1` are you referring to? 

I do plan to enable some PR validation in this repo but that will be a follow-up to my link updates.

**Comment by pakrym** [comment]
🤦‍♂ wrong repo...

**Comment by chidozieononiwu** [comment]
> Add a script that will generate the quick links table as well
> as verify that all the links work correctly.
> @kaerm @adrianhall Can you guys please take a look. Right now this is only for .NET but I'm actively planning to update this PR with the other languages as well. I just wanted to get something out for review.
> @AlexGhiondea @chidozieononiwu could you guys have a look over the link format for .NET?

The net-quicklinks.md are all good.

**Comment by tg-msft** [comment]
It's missing all the Storage Changelog.txt files and the Batch samples are currently in the Blobs samples project.

**Comment by weshaggard** [comment]
>It's missing all the Storage Changelog.txt files and the Batch samples are currently in the Blobs samples project.

I will try to detect the inconsistent changelog references for now until they can be updated. For the Batch samples I assume this is temporary? We want to try and make things consistent so we don't have to worry about all these special cases.

**Comment by weshaggard** [comment]
Merging this to get the links fixed. Please add feed back if you see something wrong or missing. I still plan to improve the generation of these tables as well as add some PR validation to this repository.

**Pull request merged**
