### PR TITLE
UI improvements to AzureSDK Release Guidelines

### PR DESCRIPTION
**Pull request by chidozieononiwu**
- Existing site https://azure.github.io/azure-sdk/dotnet_introduction.html
- Proposed look https://chidozieononiwu.github.io/azure-sdk/dotnet_introduction.html
Resolves https://github.com/Azure/azure-sdk-tools/issues/2873

### CODE REVIEW

**Comment by weshaggard** [comment]
Just for clarity this isn't the release blog but the guidelines, policy and package index site. 

This looks great to me. Adding some more reviewers so we can have some other opinions before moving forward with the changes.

**Comment by weshaggard** [comment]
@chidozieononiwu can you also link any issues you are resolving with these changes?

**Comment by lfraleigh** [comment]
Can the search box be moved to the header?  Ideally just to the left of "Blog" and the other stuff on the right?

We also need to get additional info into the footer beyond the copyright. At a minimum, we need the trademarks, privacy policy, and terms of use links from the bottom of docs.microsoft.com.  (And don't hardcode the URLs with en-us - they should go to the person's specific locale)

**Review by JeffreyRichter — APPROVED** [review]

**Comment by chidozieononiwu** [comment]
> Can the search box be moved to the header? Ideally just to the left of "Blog" and the other stuff on the right?
> 
> We also need to get additional info into the footer beyond the copyright. At a minimum, we need the trademarks, privacy policy, and terms of use links from the bottom of docs.microsoft.com. (And don't hardcode the URLs with en-us - they should go to the person's specific locale)

Where can I find the privacy policy, terms of use e.t.c? Please can you file a detaile issue for this and I will address it at a later time?

**Pull request merged**
