### PR TITLE
Update release notes for Azure Spring March release

### PR DESCRIPTION
**Pull request by saragluna**
This PR is to update March release notes for Azure Spring:
- Added installation instructions for Azure Spring users.
- Added release highlights for Azure Spring modules.

### CODE REVIEW

**Review by yiliuTo — APPROVED** [review]
LGTM

**Comment by weshaggard** [comment]
The changes look good but I'm curious what we can or should do to get our automation to pick-up these releases. If you guys are interested please work with @chidozieononiwu and/or myself and we can help get you integrated.

**Comment by saragluna** [comment]
@weshaggard thanks for the info and we're definitely interested in automating this. We will follow up with @chidozieononiwu.

**Comment by saragluna** [comment]
@chidozieononiwu do we already some guidelines on how to integrate this?

**Comment by weshaggard** [comment]
Have a look at the generated PR https://github.com/Azure/azure-sdk/pull/263 it looks like the spring libraries are already getting pulled in. I mistakenly thought that we might be filtering them. Please review and make suggestions to those automated PRs for the release notes.

**Comment by saragluna** [comment]
@weshaggard the https://github.com/Azure/azure-sdk/issues/263 is an issue, are you referring to another PR?

**Comment by weshaggard** [comment]
Oops missed a character in my copy/paste. I was referring to https://github.com/Azure/azure-sdk/pull/2630.

**Comment by saragluna** [comment]
@weshaggard @chidozieononiwu just left a comment here https://github.com/Azure/azure-sdk/pull/2630/files#r604614339.

**Pull request merged**
