### PR TITLE
[docs] README template & example

### PR DESCRIPTION
**Pull request by mmacy**
Adds:

* `README-TEMPLATE.md`
* `README-EXAMPLE.md`

Removes:

* `EXAMPLE-README.md`

### CODE REVIEW

**Comment by bterlson** [comment]
+1000.

**Comment by mmacy** [comment]
@bterlson @Petermarcu How's this looking? Any changes required prior to merge? Would love to put a stamp on this so I can finalize the other docs surrounding this guidance.

**Comment by bterlson** [comment]
Yep, I think this is good to go. I'm assuming we can iterate as required? For example, we will at some point need TypeScript-specific project configuration (plan to put this under getting started). We'll also probably want a standard version table which maps library versions to supported service versions.

**Comment by mmacy** [comment]
Thanks for the merge, @Petermarcu.

Yes, @bterlson, iteration is fine in this template as long as it doesn't pin it to a specific language. Those types of lang-specific guidance bits I envision being up to the implementer of the template. That is, lang-specific items wouldn't appear in this template, but the engineer writing the README for language X based on this template would it to their README. The template shouldn't be so rigid as to prevent that type of inclusion.

Another option is providing language-specific guidance in another doc, or as Peter had mentioned, README templates based on this one, but idiomatic for each language. I worry on the latter about consistency drift, but perhaps with CODEOWNERS entries we could minimize that.

**Pull request merged**
