### PR TITLE
[Typescript] Updating github.io links to individual packages

### PR DESCRIPTION
**Pull request by KarishmaGhiya**
Updating github.io links to individual packages after the doc restructuring for JS/TS

### CODE REVIEW

**Comment by kaerm** [comment]
The release notes were mentioning specific versions of preview libraries - shouldn't they link to that specific preview site? @KarishmaGhiya

**Comment by KarishmaGhiya** [comment]
@kaerm So we don't have documentation generated for all the preview versions. This documentation only has either the latest preview or last two previews or latest preview and GA. So I am just linking them to the landing page and let them pick which version documentation the users want from the ones available

**Comment by kaerm** [comment]
@KarishmaGhiya If we don't have them then I guess this is fine. Last question - why is there no Cosmos in the main TOC?

**Comment by KarishmaGhiya** [comment]
@kaerm  There's something wrong, it should have been there. Scott pointed out the same thing. I am going to investigate into this.

**Comment by KarishmaGhiya** [comment]
@kaerm @ramya-rao-a The cosmos package is marked as private, this is the reason why it's not listed yet on the indexpage in the docs

**Comment by ramya-rao-a** [comment]
All 4 release notes being updated here are for old releases
The new reference links will not match the package released during those releases.

I would suggest to not make these changes at all. 
Providing references docs for a wrong version is not better than 404

The latest release notes for November use the right links, so that should be enough

**Comment by KarishmaGhiya** [comment]
@ramya-rao-a @kaerm In that case I really recommend to update the "Unified SDK" link here to the latest release https://azure.microsoft.com/en-us/downloads/

Because if you do a search for "Azure SDK" then this link is the first that pops up

**Comment by weshaggard** [comment]
>Providing references docs for a wrong version is not better than 404

I disagree. We should not have any dead links we should either update them to something or remove them. It makes us look pretty bad when they 404.

**Comment by ramya-rao-a** [comment]
In that case, I would remove the reference links altogether.

**Comment by adrianhall** [comment]
I haven't seen any more updates to this since the last comments.  More coming?  What's the status?

**Comment by weshaggard** [comment]
This is no longer interesting after I cleaned up links in https://github.com/Azure/azure-sdk/pull/780.

**Pull request closed without merging**
