### PR TITLE
Check for changed files to see why cache is not updating

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Comment by weshaggard** [comment]
@chidozieononiwu can you please have a look at the git diff that is happening in the PR process? It seems like the lock file updates you have done recently don't match what happens when we do the install in CI.

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu can you please have a look at the git diff that is happening in the PR process? It seems like the lock file updates you have done recently don't match what happens when we do the install in CI.

I have resolved the lock file difference. We can approve and merge this PR.

**Review by chidozieononiwu — APPROVED** [review]

**Comment by weshaggard** [comment]
Thanks for fixing @chidozieononiwu did you setup something so that we can easily get this updated for the next time?

**Pull request merged**
