### PR TITLE
Migrate JS metadata to generate desired ToC layout

### PR DESCRIPTION
**Pull request by danieljurek**
Update metadata for ToC auto-generation. See review site at: https://review.docs.microsoft.com/en-us/javascript/api/overview/azure/?branch=djurek%2Ftoc-autogeneration-iteration&view=azure-node-latest for a preview of a ToC generated using the new automation backed by the metadata in this PR. 

@benbp -- PTAL

### CODE REVIEW

**Comment by danieljurek** [comment]
CI is failing on broken links... we might need to adjust versioning in here or in main to get this passing. https://dev.azure.com/azure-sdk/public/_build/results?buildId=1387004&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=036ed663-514a-59f3-0c88-23d2cf182147

**Comment by benbp** [comment]
So this is generated via https://github.com/Azure/azure-sdk-for-js/pull/19915 ?

**Review by benbp — APPROVED** [review]

**Comment by m-sk84** [comment]
hi everybody how are you today and I want to talk with you before some thing right now after but I think so some people his won't die before me why🤣🤣🤣

**Comment by m-sk84** [comment]
I want to speak with you before the phone I need something because everybody is joking and not good I don't know why before the money or what I am finished not have children with her friend problem but the people what doing like this one

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Ben Broderick Phillips ***@***.***>
‏‏تم الإرسال: Thursday, February 24, 2022 1:36:47 AM
إلى: Azure/azure-sdk ***@***.***>
نسخة: Subscribed ***@***.***>
‏‏الموضوع: Re: [Azure/azure-sdk] [Draft] Migrate JS metadata to generate desired ToC layout (PR #3942)


@benbp approved this pull request.

**Comment by danieljurek** [comment]
CI is not reporting but it did pass -- https://dev.azure.com/azure-sdk/public/_build/results?buildId=1389131&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=91e3dae1-85a3-4151-849e-d95055151d6f

**Comment by m-sk84** [comment]
لا اعرف افكر في اشياء كثيره ولا اعرف مالحل امشي مع الحياه ولا اعرف ما سا اواجهه امامي هل حزن ام فرح ؟؟

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Daniel Jurek ***@***.***>
‏‏تم الإرسال: Thursday, February 24, 2022 2:43:29 AM
إلى: Azure/azure-sdk ***@***.***>
نسخة: m-sk84 ***@***.***>; Comment ***@***.***>
‏‏الموضوع: Re: [Azure/azure-sdk] Migrate JS metadata to generate desired ToC layout (PR #3942)


CI is not reporting but it did pass -- https://dev.azure.com/azure-sdk/public/_build/results?buildId=1389131&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=91e3dae1-85a3-4151-849e-d95055151d6f

**Comment by m-sk84** [comment]
P {margin-top:0;margin-bottom:0;}

**Pull request merged**
