### PR TITLE
Add azure-ai-generative to package list

### PR DESCRIPTION
**Pull request by diondrapeck**

### CODE REVIEW

**Comment by weshaggard** [comment]
Why are you adding this package manually? It should get added automatically once this package is published.

**Comment by diondrapeck** [comment]
> Why are you adding this package manually? It should get added automatically once this package is published.

The [onboarding instructions doc](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-docs#service-level-overviews) said I should add it manually. I can close this PR if that's incorrect.

image

**Comment by weshaggard** [comment]
@danieljurek can you clarify that documentation? In general as long is the package goes through our normal release processes it will get added automatically to the csv file. You might need to manually tweak some fields in here for docs purposes but the package itself shouldn't need to be added manually.

**Comment by diondrapeck** [comment]
> @danieljurek can you clarify that documentation? In general as long is the package goes through our normal release processes it will get added automatically to the csv file. You might need to manually tweak some fields in here for docs purposes but the package itself shouldn't need to be added manually.

Thanks for the clarification!

**Pull request closed without merging**
