### PR TITLE
Remove alpha Communication packages from release notes

### PR DESCRIPTION
**Pull request by timovv**

### CODE REVIEW

**Comment by timovv** [comment]
@weshaggard: do you have any idea why this package has alpha versions making their way into the automated release note PRs? It seems to have showed up in the CSV as well: https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/js-packages.csv#L17

**Comment by weshaggard** [comment]
@timovv it looks like someone set the latest tag of this package to the alpha version https://www.npmjs.com/package/@azure/communication-phone-numbers?activeTab=versions. We probably need to reach out to the package owner to understand why this is the case.

**Comment by weshaggard** [comment]
Actually I think the issue is https://github.com/Azure/azure-sdk-for-js/blob/%40azure/communication-phone-numbers_1.2.0-alpha.20230307.3/sdk/communication/communication-phone-numbers/package.json#L3. 

@guoqing2023 why did you set the version explicitly to alpha in the package.json in PR https://github.com/Azure/azure-sdk-for-js/pull/25124

**Review by weshaggard — APPROVED** [review]

**Comment by jeremymeng** [comment]
@weshaggard is it possible to and should we try limitting release pipelines to certain branches?  main, releases/*, hotfix/*

**Comment by weshaggard** [comment]
@jeremymeng how would that help with this issue? This was released out of main. 

We could add branch filtering for release but I'd like to better understand why first and if you feel it is helpful submit an issue and we can discuss it.

**Comment by jeremymeng** [comment]
@weshaggard it was released out of another branch in this build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2612994&view=results

I think limiting to a handful branch could make people be more cautious, however it doesn't really prevent people from, say, push to those limited branches then release.

**Comment by weshaggard** [comment]
Oh, interesting I did miss that. However, someone could have done the same thing in main. I'm still not sure it is worth adding the branch blocking. Interesting enough this is the first time someone has tried to release a alpha package that I'm aware of.

**Comment by jeremymeng** [comment]
yes, agree that it will not be useful when it can be easily worked around.

**Pull request merged**
