### PR TITLE
Bulk Metadata Updates

### PR DESCRIPTION
**Pull request by MeeraDi**
Add MSDocService=azure-functions where ServiceName=Functions

### CODE REVIEW

**Comment by MeeraDi** [comment]
Hi @danieljurek this PR is ready for review and merge.

**Comment by MeeraDi** [comment]
Hi @danieljurek this PR is ready for review and merge.

**Review by danieljurek — CHANGES_REQUESTED** [review]
The following packages would be unnecessarily onboarded by this change, please remove the `azure-functions` value in `MSDocService` field: 

Microsoft.Azure.Functions.Analyzers
Microsoft.Azure.Functions.Authentication.WebAssembly
Microsoft.Azure.Functions.Extensions
Microsoft.Azure.Functions.Worker.ApplicationInsights
Microsoft.Azure.Functions.Worker.Extensions.Abstractions
Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights
Microsoft.Azure.Functions.Worker.Extensions.CosmosDB
Microsoft.Azure.Functions.Worker.Extensions.EventGrid
Microsoft.Azure.Functions.Worker.Extensions.EventHubs
Microsoft.Azure.Functions.Worker.Extensions.Http
Microsoft.Azure.Functions.Worker.Extensions.Kafka
Microsoft.Azure.Functions.Worker.Extensions.Kusto
Microsoft.Azure.Functions.Worker.Extensions.OpenApi
Microsoft.Azure.Functions.Worker.Extensions.RabbitMQ
Microsoft.Azure.Functions.Worker.Extensions.SendGrid
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus
Microsoft.Azure.Functions.Worker.Extensions.SignalRService
Microsoft.Azure.Functions.Worker.Extensions.Sql
Microsoft.Azure.Functions.Worker.Extensions.Storage
Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs
Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues
Microsoft.Azure.Functions.Worker.Extensions.Storage.Tables
Microsoft.Azure.Functions.Worker.Extensions.Tables
Microsoft.Azure.Functions.Worker.Extensions.Timer
Microsoft.Azure.Functions.Worker.Extensions.Warmup
Microsoft.Azure.Functions.Worker.ItemTemplates
Microsoft.Azure.Functions.Worker.ProjectTemplates
Microsoft.Azure.Functions.Worker.Sdk
Microsoft.Azure.Functions.Worker.Sdk.Analyzers
Microsoft.Azure.Functions.Worker.Sdk.Generators
Microsoft.Azure.WebJobs
Microsoft.Azure.WebJobs.Core
Microsoft.Azure.WebJobs.CosmosDb.ChangeProcessor
Microsoft.Azure.WebJobs.Extensions
Microsoft.Azure.WebJobs.Extensions.ApplicationInsights
Microsoft.Azure.WebJobs.Extensions.CosmosDB
Microsoft.Azure.WebJobs.Extensions.DocumentDB
Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers
Microsoft.Azure.WebJobs.Extensions.EdgeHub
Microsoft.Azure.WebJobs.Extensions.Kafka
Microsoft.Azure.WebJobs.Extensions.MobileApps
Microsoft.Azure.WebJobs.Extensions.NotificationHubs
Microsoft.Azure.WebJobs.Extensions.OpenApi
Microsoft.Azure.WebJobs.Extensions.OpenApi.Configuration.AppSettings
Microsoft.Azure.WebJobs.Extensions.OpenApi.Core
Microsoft.Azure.WebJobs.Extensions.RabbitMQ
Microsoft.Azure.WebJobs.Extensions.SendGrid
Microsoft.Azure.WebJobs.Extensions.Sql
Microsoft.Azure.WebJobs.Extensions.Timers.Storage
Microsoft.Azure.WebJobs.Extensions.Twilio
Microsoft.Azure.WebJobs.Host.Storage
Microsoft.Azure.WebJobs.Host.TestCommon
Microsoft.Azure.WebJobs.ItemTemplates
Microsoft.Azure.WebJobs.Logging
Microsoft.Azure.WebJobs.Logging.ApplicationInsights
Microsoft.Azure.WebJobs.ProjectTemplates
Microsoft.Azure.WebJobs.Script.Abstractions
Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator
Microsoft.Azure.WebJobs.Sources

**Comment by MeeraDi** [comment]
Discarding as the purpose of this PR was to add the azure-functions value.

**Comment by danieljurek** [comment]
The list I provided was not exhaustive. Just the items in the list need the `MSDocService` entry to be empty.

**Comment by MeeraDi** [comment]
@danieljurek updated to remove the azure-functions value from the packages you listed. I also reverted the changes that were pulled in from a merge conflict. The PR only contains updates to the MSDocService values.

**Comment by danieljurek** [comment]
@MeeraDi -- The list of extra packages I'm seeing onboarded is: 

Microsoft.Azure.Functions.Worker.Sdk
Microsoft.Azure.WebJobs
Microsoft.Azure.WebJobs.Core
Microsoft.Azure.WebJobs.CosmosDb.ChangeProcessor
Microsoft.Azure.WebJobs.Extensions
Microsoft.Azure.WebJobs.Extensions.ApplicationInsights
Microsoft.Azure.WebJobs.Extensions.CosmosDB
Microsoft.Azure.WebJobs.Extensions.DocumentDB
Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers
Microsoft.Azure.WebJobs.Extensions.EdgeHub
Microsoft.Azure.WebJobs.Extensions.Kafka
Microsoft.Azure.WebJobs.Extensions.MobileApps
Microsoft.Azure.WebJobs.Extensions.NotificationHubs
Microsoft.Azure.WebJobs.Extensions.OpenApi
Microsoft.Azure.WebJobs.Extensions.OpenApi.Configuration.AppSettings
Microsoft.Azure.WebJobs.Extensions.OpenApi.Core
Microsoft.Azure.WebJobs.Extensions.RabbitMQ
Microsoft.Azure.WebJobs.Extensions.SendGrid
Microsoft.Azure.WebJobs.Extensions.Sql
Microsoft.Azure.WebJobs.Extensions.Timers.Storage
Microsoft.Azure.WebJobs.Extensions.Twilio


Some of these items (like `Microsoft.Azure.WebJobs.CosmosDb.ChangeProcessor` were in the last list provided)

**Pull request closed without merging**
