### PR TITLE
no runtime configuration for c.

### PR DESCRIPTION
**Pull request by barcharcraz**
After discussion on friday the 15th we came to the conclusion that it indeed does not make any sense to have run-time configuration for the c sdk via config files or env vars. IOT clients probably won't even have a filesystem of environment block.

Note that the client can still be configured at runtime, but only by the user/caller, not by the client librariy itself.

### CODE REVIEW

**Comment by adrianhall** [comment]
I have a query about this - we aren't supporting Linux as well as IoT?  Only IoT?

No objections - I think in C that the customer should be in control.  However, I think we want to word it positively.  "MUST provide all configuration through an explicit client constructor call.  Do not magically configure the client based on environment variables, for example." or something similar.

**Comment by barcharcraz** [comment]
We are supporting linux (and kinda windows), but IoT is the main target, and so we can't rely on env vars to control much of anything

At most we could provide an optional set of functions like `az_bla_bla_client_init_from_conf_file(...)` on systems where files have meaning.

**Comment by barcharcraz** [comment]
There are existing bits of the client configuration section that may be more appropriate to reword in the positive. For example:
> {% include requirement/MUST id="clang-config-global-config" %} use relevant global configuration settings either by default or when explicitly requested to by the user, for example by passing in a configuration object to a client constructor.

Could be something like:

**Comment by barcharcraz** [comment]
Hmm, during the meeting there was some trouble understanding the intent of these options. I think they need to be worded positively and also need examples

**Comment by barcharcraz** [comment]
OK I'm going to merge this and base the examples and clarifications off it.

**Pull request merged**
