### PR TITLE
(chore): remove the dps provisioning service client

### PR DESCRIPTION
**Pull request by anthonyvercolano**
This service client was never implemented.

### CODE REVIEW

**Review by sima-zhu — APPROVED** [review]

**Comment by weshaggard** [comment]
Removing this will not help as it will come back since it is published on pypi https://pypi.org/project/azure-iothub-provisioningserviceclient/. @anthonyvercolano is there a plan to remove it from pypi?

**Comment by anthonyvercolano** [comment]
Hopefully @weshaggard I'm going to address your question.  We would be replacing the package with a stub that simply informs that this client was obsolete.  Hopefully this would remove any links to the old documentation.  We can't actually delete the package because the name could (and has been in the past) highjacked.

@cartertinney Anything you want to add?

**Comment by cartertinney** [comment]
@weshaggard Is there a way we can stop ingesting docs from PyPi? We don't have plans to remove it (as Tony mentioned, that creates a security vulnerability), but we don't wish to update it any further if not necessary (contrary to what Tony said above).

Is there a way to simply unlink this package from populating documentation?

**Comment by weshaggard** [comment]
Give this package is on pypi we don't have good way to prevent it from being found and pulled into this csv but we can set a field for it such that we hide it from the package index and other processing such as docs. 

As you can see the automation already added this entry back https://github.com/Azure/azure-sdk/pull/4303/files#diff-65b465be37ec6b4b1cf459e08f5acb2df1fa4a9df69d052eaeae0aec21f59557R298. I suggest just setting the Hide field for this package to true. You can see more about the field documentation at https://github.com/Azure/azure-sdk/blob/main/eng/README.md. It should be as simple as setting the Hide column to true for this package.

**Pull request merged**
