### PR TITLE
Remove codeowners baseline file

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Comment by weshaggard** [comment]
@ahsonkhan can you please expose the Azure org as public on your profile? See https://aka.ms/azsdk/repoaccess for instructions

**Comment by ahsonkhan** [comment]
@weshaggard It seems like accessing Enterprise settings and policies as listed here requires me to have a GitHub Enterprise account.
https://docs.github.com/en/enterprise-server@3.2/admin/user-management/managing-organizations-in-your-enterprise/configuring-visibility-for-organization-membership

In a regular (non-enterprise) GitHub account, I don't see those settings. How do I do that otherwise, or should I opt in to "try enterprise" to fix this?

https://github.com/settings/enterprises
image

**Comment by ahsonkhan** [comment]
Ok, I figured it out. It's under the "Your organizations" setting:

https://github.com/orgs/Azure/people

This doc link helped:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership

We may want to update the instructions here to mention that link to set the GitHub membership to public for non-enterprise users, after they join the Azure org:
https://eng.ms/docs/products/azure-developer-experience/onboard/access

image

**Review by JimSuplizio — APPROVED** [review]
@weshaggard, I reran the linter pipeline this morning, since the owner extractor pipeline would have already finished today's run. The data is updated, both users are now public and azure-sdk, for the moment, [no longer needs a baseline file](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3316452&view=logs&j=9eca7197-01ad-568c-e027-1e3b6441a680&t=69736b42-1dbb-535b-4b69-903bc4557a55&l=13)

**Comment by JimSuplizio** [comment]
> Ok, I figured it out. It's under the "Your organizations" setting:
> 
> https://github.com/orgs/Azure/people
> 
> This doc link helped: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership
> 
> We may want to update the instructions here to mention that link to set the GitHub membership to public for non-enterprise users, after they join the Azure org: https://eng.ms/docs/products/azure-developer-experience/onboard/access
> 
You should just be able to go to the [Azure org and query for you name](https://github.com/orgs/Azure/people). From there you change the org visibility for yourself. See below.
image

**Pull request merged**
