### PR TITLE
[Communication] Add iOS Calling GA May release notes

### PR DESCRIPTION
**Pull request by jorgegarchirota**

### CODE REVIEW

**Comment by jorgegarchirota** [comment]
@vcolin7 , @czubair , @azure-sdk.  can you please take a look?

**Comment by jorgegarchirota** [comment]
#sign-off

**Review by tjprescott — CHANGES_REQUESTED** [review]
This PR is not necessary. See: https://github.com/Azure/azure-sdk/pull/2845

**Comment by jorgegarchirota** [comment]
Thanks @tjprescott  👍

**Comment by tjprescott** [comment]
No problem. Generally speaking @jorgegarchirota, our team will handle the release notes, compiling them from the CHANGELOG. So you should only need to verify that they get published.

**Pull request closed without merging**
