### PR TITLE
Rust features should use underscores

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Comment by heaths** [comment]
@RickWinter @JeffreyRichter I'd like to introduce this requirement for the reason stated in the content - to provide a consistent experience using underscores since they are required to *use* crates (so we use them in crate naming), and when specifying features so Azure devs can always expect to use underscores everywhere.

**Comment by JeffreyRichter** [comment]
Sounds good to me.

**Comment by RickWinter** [comment]
@heaths, Are the pipeline changes intended?

**Comment by heaths** [comment]
No. I'm not even sure how those got in there. I'll remove them...

**Review by JeffreyRichter — APPROVED** [review]

**Pull request merged**
