### PR TITLE
Update latest track 2 mgmt libraries

### PR DESCRIPTION
**Pull request by nickzhums**

### CODE REVIEW

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
@jongio this is going to cause more conflict with your work in progress PR. Do you want us to hold off on merging this PR?

**Comment by nickzhums** [comment]
@jongio  @weshaggard I see that in the latest file those libraries already have the "mgmt" labels, however they haven't shown up on this page yet (https://azure.github.io/azure-sdk/releases/latest/mgmt/python.html)

Are we just waiting for them to update?

**Comment by nickzhums** [comment]
@weshaggard kindly ping

**Comment by weshaggard** [comment]
@nickzhums do you have an example? I will say with Jon's recent changes the library must have type=mgmt and new=true to show up in the mgmt table in the package index. So if there are cases that are missing make sure both of those columns are set correctly.

**Comment by weshaggard** [comment]
You also need to resolve the current file conflicts before we can merge this.

**Comment by nickzhums** [comment]
@weshaggard  sorry, I didn't realize there was a "new" field. I will edit the files again and make an update, thanks

**Pull request closed without merging**
