### PR TITLE
Bulk Metadata Update

### PR DESCRIPTION
**Pull request by MeeraDi**
Added msdocservicevalue=azure-functions to 12 instances where ServiceName=Functions

### CODE REVIEW

**Comment by MeeraDi** [comment]
@danieljurek this PR is ready for review and merge.
Thanks

**Review by danieljurek — CHANGES_REQUESTED** [review]
The following packages would be unnecessarily onboarded by this change, please remove the azure-functions value in MSDocService field:


azure-functions-java-core-library
azure-functions-java-library-cosmosdbcassandra
azure-functions-java-library-rabbitmq
azure-functions-java-library-signalr
azure-functions-java-spi

**Comment by MeeraDi** [comment]
Discarding the changes in this file as they all add the azure-function value to MSDocService.

**Comment by danieljurek** [comment]
The list I provided was not exhaustive. Just the items in the list need the `MSDocService` entry to be empty.

**Comment by MeeraDi** [comment]
@danieljurek updated to remove the azure-functions value from the packages you listed.

**Comment by danieljurek** [comment]
The following packages would be unnecessarily onboarded by this change, please remove the azure-functions value in MSDocService field:

azure-functions-java-library-kusto
azure-functions-java-core
azure-functions-java-library-sql

**Pull request closed without merging**
