### PR TITLE
Update Track 2 Python packages

### PR DESCRIPTION
**Pull request by nickzhums**

### CODE REVIEW

**Review by yonzhan — APPROVED** [review]
LGTM

**Comment by jsntcy** [comment]
@nickzhums, will this change update this doc https://azure.github.io/azure-sdk/releases/latest/python.html?

**Comment by nickzhums** [comment]
> @nickzhums, will this change update the doc https://azure.github.io/azure-sdk/releases/latest/python.html?

yes

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
The broken link is related to https://github.com/Azure/azure-sdk/pull/2015 so merging.

**Comment by nickzhums** [comment]
thanks @weshaggard

**Pull request merged**
