### PR TITLE
Add requirement for model factories in .NET

### PR DESCRIPTION
**Pull request by heaths**
Based on PR feedback, add requirement about overloading ModelFactory methods.

### CODE REVIEW

**Comment by tg-msft** [comment]
I think we might want this as a recommendation in the general versioning guidance because this is how you'll update any API with optional parameters (i.e., we do the same thing to client operation methods when we add a param in Storage).  This is apparently undocumented versioning guidance from the .NET folks and I think we should write it down until they add it somewhere.

**Comment by heaths** [comment]
To clarify, this is a request to move something like it to https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning.

**Comment by heaths** [comment]
@KrzysztofCwalina, do you agree with Ted, though? Should I move this to general versioning?

**Comment by KrzysztofCwalina** [comment]
@heaths, it might be better in general guidelines, but I am ok with checking it in as-is and then generalizing it later. Similar guideline will be added to .NET guidelines, and so we will have to refactor at some point anyway.

**Pull request merged**
