### PR TITLE
Do not document metapackages

### PR DESCRIPTION
**Pull request by danieljurek**
@weshaggard -- Do we want to show metapackages? If not, I propose we hide them.

### CODE REVIEW

**Comment by weshaggard** [comment]
I would like to have the python team decide whether or not we should hide these or not.

**Comment by danieljurek** [comment]
@lmazuel -- Should we be showing metapackages? `azure-keyvault` was onboarded into here and we cannot build ref docs for it. I'm trying to determine if we should be hiding these to keep them from up the docs build or if we need to detect them by another means.

**Comment by lmazuel** [comment]
@danieljurek  Don't show them anymore, those are Python 2 only, and we don't support Python 2. And even if we were to support Python 2, those were implementation details.

**Comment by danieljurek** [comment]
I'm only aware of `azure-keyvault` and it's already explicitly excluded here: https://github.com/Azure/azure-sdk-for-python/blob/main/eng/scripts/Language-Settings.ps1#L303 ... If we need to set `Hide` on metapackages going forward we can do that in another PR.

**Pull request closed without merging**
