### PR TITLE
Added event hubs change log highlights

### PR DESCRIPTION
**Pull request by YijunXieMS**

### CODE REVIEW

**Comment by YijunXieMS** [comment]
> None of the suggested changes are major changes. This isn't the CHANGELOG. I think what you are saying is "We added the event processor to support an easier architecture for processing events", but I'm not sure and I didn't get that from this.

Hi @adrianhall It's true that eventhubs 5.0.0b6 doesn't have major changes. The main change from pull model to push model was done in b5. So we don't need to mention event hubs in this file for this release since there are no major changes?

**Comment by annatisch** [comment]
@YijunXieMS - there are a major changes:
- event processing callback went from batch to single event.
- send method was removed, replaced with Batch sending exclusively via send_batch

**Comment by adrianhall** [comment]
I think (based on Annas comment):


  *   The semantics for sending events was changed.  `send_event` now sends a single event, whereas `send_batch` sends a batch of events.

Link the individual functions to the API documentation, and obviously make sure the function names are correct.

**Comment by YijunXieMS** [comment]
I keep the two major changes that Anna proposed and use the same text from the HISTORY.md of event hubs.

**Pull request merged**
