### PR TITLE
Automatically add reviewers on label assignment

### PR DESCRIPTION
**Pull request by mario-guerra**
Add myself, Ronnie, and Scott as PR reviewers when the 'SDK Deprecation' label is used.

### CODE REVIEW

**Comment by jsquire** [comment]
//fyi: @JimSuplizio, for additional thoughts.

**Comment by mario-guerra** [comment]
Can we commit this change in the interim till the new system comes online?

**Comment by jsquire** [comment]
It really does not make sense to do so.   If we accept this change now, you'll lose the functionality in a week or two when Fabric Bot is removed.  At that point, we'll be waiting for an enhancement to how data is represented in CODEOWNERS before we could create this rule.  If this is a rule that you'll want us to consider adding, please [open an issue](https://github.com/Azure/azure-sdk-tools/issues) in the Azure SDK Tools repository, tag with "GitHub Event Processor" and (optionally, but preferably) assign to Jim and myself.   That will ensure that we don't lose track of it.

**Comment by mario-guerra** [comment]
@jsquire done https://github.com/Azure/azure-sdk-tools/issues/5944

**Pull request closed without merging**
