### PR TITLE
Replace Azure icon with Azure SDK glyph

### PR DESCRIPTION
**Pull request by scottaddie**
Update the github.io site to use the newly designed Azure SDK logo. The Twitter account will soon be updated to use the same logo.

**Preview of change:**
image

/cc: @weshaggard @jongio

### CODE REVIEW

**Comment by jongio** [comment]
Please don't merge until we discuss the actual logo. Thanks

**Review by jongio — CHANGES_REQUESTED** [review]
Let's discuss the logo

**Comment by weshaggard** [comment]
@scottaddie @jongio has there been any discussion on taking this logo update yet?

**Comment by jongio** [comment]
@lfraleigh is working with design team.

**Comment by cglong** [comment]
Have we considered replacing the old Azure logo with the new(ish) "A" logo in the meantime?

**Comment by scottaddie** [comment]
Updated logo preview:
image

**Review by jongio — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
