### PR TITLE
Update to clarify that cancellation and timeouts are not separate entities

### PR DESCRIPTION
**Pull request by ramya-rao-a**
The header `Cancellation & Timeouts` had me thinking that both needed to implemented as 2 separate options i.e provide cancellation token as well as a separate timeout option.

On discussion with @bterlson, it was clarified that the cancellation mechanism is expected to have the timeout logic in it and a separate timeout is not needed.

This PR is to update the header to clarify this.

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
cc @jsquire as you plan to support both cancellation token and timeouts for your work in Event Hubs .Net sdk

**Comment by jsquire** [comment]
> cc @jsquire as you plan to support both cancellation token and timeouts for your work in Event Hubs .Net sdk

The underlying track one implementation for .NET relies on timeouts and does some ...interesting... things with them at the AMQP level that I don't yet fully understand.   The track one implementation also does not fully support or honor cancellation up and down the stack.

Since the preview is using the track one constructs to perform the communication with the service, this is something that will need to be deferred until a deeper analysis can be done and better understanding reached of the current design.   It also will require the planned overhaul of the AMQP infrastructure from track one in order to ensure cancellation is a first-class concept.

**Comment by adrianhall** [comment]
You have changed the wrong file.  General guidelines are now in the general/ folder.  

Also, this should be done as an issue (Design Guidelines Change Request).

**Comment by ramya-rao-a** [comment]
> You have changed the wrong file. General guidelines are now in the general/ folder.

@adrianhall I don't see a cancellation related file in the general folder at https://github.com/Azure/azure-sdk/tree/master/docs/design/general

**Comment by adrianhall** [comment]
It's in incorporated into the APIShape.mdk file.  I don't think this PR makes sense in the current guidelines.

**Comment by ramya-rao-a** [comment]
This PR makes sense as long as the file `Cancellations.mdk` is being used in our guidelines.

**Pull request merged**
