### PR TITLE
Merge March Release Notes with what was in Blog

### PR DESCRIPTION
**Pull request by jongio**

### CODE REVIEW

**Review by lilyjma — APPROVED** [review]
LGTM

**Comment by Mohit-Chakraborty** [comment]
@czubair , can we use this model going forward? Then, no one has to spend time updating highlights in index.md.

**Review by Mohit-Chakraborty — APPROVED** [review]

**Review by czubair — APPROVED** [review]

**Comment by czubair** [comment]
> @czubair , can we use this model going forward? Then, no one has to spend time updating highlights in index.md.
> Or, is it a feedback loop where the notes initially written here are used to kickstart stuff in the blog and the published notes are put back here?

Let's talk about it in our release sync Thurs :)

**Comment by jongio** [comment]
Release note highlights are sourced in the index.md file of the release and then copied to blog.

**Pull request merged**
