### PR TITLE
[General] remove readme guidance in favor of normative reference

### PR DESCRIPTION
**Pull request by bterlson**

### CODE REVIEW

**Comment by bterlson** [comment]
This PR removes some of the inline README guidance (some of which had java words that were frightening and confusing to me) in favor of linking to @mmacy's README template.

**Comment by mmacy** [comment]
@bterlson One thing to note is that external (non-MSFT) readers won't be able to hit that doc on the staging site. I'll be moving a version of it into this repo today--you could hold off and link to that once I've got it in there, or just roll with this for now and I can update this doc once completed.

**Comment by bterlson** [comment]
@mmacy ahh ok, happy to hold off then! Ping me in case I miss when the template lands.

**Comment by mmacy** [comment]
@bterlson README template and example PR opened: #214

**Comment by mmacy** [comment]
@bterlson #214 has been merged, you're GTG to update the README link to point to `/docs/README-TEMPLATE.md`

**Comment by bterlson** [comment]
Thanks @mmacy, updated the guidelines!

**Pull request merged**
