### PR TITLE
Make table to wrap words from all content by words

### PR DESCRIPTION
**Pull request by vhvb1989**
fixes: https://github.com/Azure/azure-sdk/issues/2036
fixes: https://github.com/Azure/azure-sdk/issues/2024

Applying wrap to table style to avoid right grow.
Will keep the table growing down like:

image

### CODE REVIEW

**Comment by vhvb1989** [comment]
@salameer  this also fixes the left menu overflow, as the table will grow down instead of right.

**Comment by vhvb1989** [comment]
Also making all tables to be the same width,

Before:
image

After
image

**Comment by jongio** [comment]
@vhvb1989 - Please have a look at the "All" tab, some of the names do not have spaces and might not wrap with this fix.  Can you send a screenshot to verify?  Thanks,
Jon

**Comment by vhvb1989** [comment]
@jongio 
image

**Comment by vhvb1989** [comment]
@jongio I would like to replace the html table formatting and use flex layout instead. Then we can control what cells we want to let grow and the ones we want fixed size.  It is harder using raw tables.
But since that's a bigger change, I will leave it for other time in the future :D

With the current changes, the table will never override to the right. However, on bigger monitors, we could let the entire page grow to better display the table

**Comment by jongio** [comment]
This is what the right most column looks like now:
image


Can you make the last column wider?  Thanks

**Comment by vhvb1989** [comment]
@jongio sure, what about:
image

**Comment by jongio** [comment]
Can you get some cellpadding so the letters have space between the border?

**Comment by vhvb1989** [comment]
@jongio yes, I tried reducing the previous padding, here is how it looks with the original padding
image


I wonder if we want padding for the non-text cells (the ones in the middle)

**Comment by jongio** [comment]
I would say we can reduce the padding for the middle columns.

**Comment by vhvb1989** [comment]
Good, @jongio , this is how it look removing the left and right padding from the buttons (just keeping top and bottom padding)

image

**Review by jongio — APPROVED** [review]

**Comment by vhvb1989** [comment]
another change to update the language nav filters:
image

**Comment by vhvb1989** [comment]
Live demo: https://vhvb1989.github.io/azure-sdk/releases/latest/index.html

**Review by jongio — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
