### PR TITLE
Add ALL_PROXY

### PR DESCRIPTION
**Pull request by bterlson**
It looks like .NET us using ALL_PROXY in some cases. We should commit to ALL_PROXY across the SDK if it's necessary!

### CODE REVIEW

**Comment by adrianhall** [comment]
I think the major thing here is

a) Do we believe that ALL_PROXY should be supported by all languages, OR
b) Do we believe that ALL_PROXY should not be supported, because HTTP/HTTPS_PROXY are already available.

Since we do AMQP type protocols, I'm going to lean towards (a) personally, but will let the architects weigh in.

If we support (a), then Python, JS, and Java will need to support it.
If we support (b), then .NET will need to remove it.

**Comment by JeffreyRichter** [comment]
This is only for non-HTTP protocols? If so, we should be more explicit about this in the guidelines. 
If its for all protocols, then what takes precedence if both HTTP and ANY proxy exist?

**Comment by bterlson** [comment]
Here is a relevant PR on the JS side: https://github.com/Azure/azure-sdk-for-js/pull/6900/files.

ALL_PROXY would be used for HTTP protocol IF HTTP_PROXY and HTTPS_PROXY are not set. This is one of the behaviors I'm not entirely sure about - ISTM that ALL_PROXY should only be used for SOCKS proxies which we don't support, but if we do support it, then all traffic, http or otherwise, should use the ALL_PROXY.

**Comment by weshaggard** [comment]
@bterlson is this a PR we still want to take?

**Comment by Ggmfffffffff** [comment]
J

**Pull request closed without merging**
