### PR TITLE
Adding ASP.NET extensions to the .NET releases

### PR DESCRIPTION
**Pull request by kaerm**

### CODE REVIEW

**Comment by jongio** [comment]
did you run locally to make sure it renders?

**Comment by kaerm** [comment]
@jongio I didn't, don't have anything set up for that

**Comment by weshaggard** [comment]
The CI validated that the links are valid and that the site builds I suspect that is all that is needed to verify this change.

**Comment by jongio** [comment]
I like to visually look at it, just to be 100%. I've been bit before

**Comment by kaerm** [comment]
Visually tested - works

**Pull request merged**
